language: ruby
rvm: 2.4.1
before_script: gem install awesome_bot
script: awesome_bot README.md --allow-redirect --white-list https://github.com/gstn-caruso/awesome-smalltalk/blob/master/smalltalk-logo.png?raw=true,https://creativecommons.org/publicdomain/zero/1.0
